### ISSUE TITLE
Python 3.7 compatibility broken by typing import

### ISSUE THREAD

**Issue by bgyori** [cthoyt/zenodo-client#12]
This PR https://github.com/cthoyt/zenodo-client/pull/8 does `from typing import Literal` which is Python 3.8+. This results in some broken tests in the indra_cogex repo. Since this is such a simple import, is it possible to replace it to maintain compatibility? Or should zenodo-client be declared 3.8+ only?

**Comment by cthoyt** [comment]
yes I will fix this right now

**Comment by bgyori** [comment]
Great, thanks!
